FROM centos

ENV TIME_ZOME Asia/Shanghai

RUN yum update -y \
    && yum -y install gcc gcc-c++ pcre pcre-devel zlib zlib-devel automake autoconf libtool make \
    && echo "${TIME_ZOME}" > /etc/timezone \
    && ln -sf /usr/share/zoneinfo/${TIME_ZOME} /etc/localtime

COPY tar/ /home

RUN cd /home \
    && tar -xvf nginx-1.18.0.tar.gz \
    && cd nginx-1.18.0 \
    && ./configure \
    && make \
    && make install \
    && rm -rf /tmp/nginx* \
    && ln -s /usr/local/nginx/sbin/nginx /usr/sbin/nginx

#声明nginx端口
EXPOSE 80

CMD nginx -g "daemon off;"
